[workspace.package]
edition = "2021"
authors = ["José Duarte <duarte.gmj@gmail.com>"]

[workspace]
resolver = "3"
members = ["ectt-oauth"]


[workspace.dependencies]
# Local dependencies
ectt-oauth = { path = "../ectt-oauth" }

# Others
tokio = { version = "1.45.1" }
clap = { version = "4.5.39" }
oauth2 = { version = "5.0.0" }
axum = { version = "0.8.4", features = ["macros"] }
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.19" }
tokio-util = { version = "0.7.15" }
thiserror = { version = "2.0.3" }
serde = { version = "1" }
imap = { version = "3.0.0-alpha.15", default-features = false }
rustls = { version = "0.23.27" }
base64 = { version = "0.22.1" }
serde_json = { version = "1.0.104" }
