[workspace.package]
edition = "2021"
authors = ["José Duarte <duarte.gmj@gmail.com>"]

[workspace]
resolver = "3"
members = ["ectt-oauth", "ectt-oauth-demo"]


[workspace.dependencies]
# Local dependencies
ectt-oauth = { path = "../ectt-oauth" }

# Others
tokio = { version = "1.45.1" }
clap = { version = "4.5.39" }
oauth2 = { version = "5.0.0" }
